FROM node:18-alpine as builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --silent
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/package.json /app/package-lock.json /app/.next /app/public ./
RUN npm ci --production --silent
EXPOSE 3000
CMD ["npm", "start"]
