"""complete_schema

Revision ID: 03f29471eb7a
Revises: 5ed16aed064a
Create Date: 2026-05-17 17:12:52.755202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f29471eb7a'
down_revision: Union[str, None] = '5ed16aed064a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('jd_text', sa.String(), nullable=False),
    sa.Column('extracted_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ctc_min', sa.Float(), nullable=True),
    sa.Column('ctc_max', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('drive_date', sa.DateTime(), nullable=True),
    sa.Column('min_cgpa', sa.Float(), nullable=True),
    sa.Column('eligible_branches', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('drives')
    op.drop_table('student_skills')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
